---
- name: Ensure Docker network for proxy exists
  community.docker.docker_network:
    name: proxy-tier
    driver: bridge
    state: present

- name: Ensure proxy config directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/lamp/proxy/certs
    - /opt/lamp/proxy/vhost.d
    - /opt/lamp/proxy/html

- name: Deploy proxy docker-compose file
  template:
    src: proxy-compose.yml.j2
    dest: /opt/lamp/proxy/docker-compose.yml
    mode: '0644'

- name: Start nginx-proxy + Let’s Encrypt companion
  community.docker.docker_compose_v2:
    project_src: /opt/lamp/proxy
