---
- name: Ensure project directory exists
  file:
    path: /opt/lamp
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Ensure HTML subdirectory exists
  file:
    path: /opt/lamp/html
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy Dockerfile for custom PHP image
  copy:
    src: Dockerfile
    dest: /opt/lamp/Dockerfile
    mode: '0644'

- name: Copy Docker Compose file
  template:
    src: lamp-compose.yml.j2
    dest: /opt/lamp/docker-compose.yml
    mode: '0644'

- name: Deploy database test PHP file
  copy:
    src: file2.php
    dest: /opt/lamp/html/file2.php
    mode: '0644'

- name: Remove any existing lamp-web image
  community.docker.docker_image:
    name: lamp-web
    state: absent
    force_absent: yes

- name: Bring up LAMP stack (rebuild web image every time)
  community.docker.docker_compose_v2:
    project_src: /opt/lamp
    build: always
    recreate: always
    remove_orphans: true
